apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-paciente-hpa
  namespace: hackathon-28
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-paciente-deployment
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 35

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-medico-hpa
  namespace: hackathon-28
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-medico-deployment
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 35

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-agendamento-hpa
  namespace: hackathon-28
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-agendamento-deployment
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 35

