apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-paciente-deployment
  namespace: hackathon-28
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-paciente
  template:
    metadata:
      labels:
        app: api-paciente
    spec:
      containers:
      - name: api-paciente
        image: cdoiche/hackathon-28-api-paciente:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: ASPNETCORE_ENVIRONMENT
        - name: OTLP__ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: OTLP__ENDPOINT
        - name: AgendamentoServiceUrl
          value: http://api-agendamento-service
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_PACIENTE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - "-c"
              - |
                dotnet ef database update --context PacienteDbContext --no-interaction 2>&1 | tee /tmp/migration.log; cat /tmp/migration.log
      imagePullSecrets:
          - name: regcred

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-medico-deployment
  namespace: hackathon-28
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-medico
  template:
    metadata:
      labels:
        app: api-medico
    spec:
      containers:
      - name: api-medico
        image: cdoiche/hackathon-28-api-medico:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: ASPNETCORE_ENVIRONMENT
        - name: OTLP__ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: OTLP__ENDPOINT
        - name: AgendamentoServiceUrl
          value: http://api-agendamento-service
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_MEDICO
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: RABBIT_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: RABBITMQ_HOST
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: RABBITMQ_PORT
      imagePullSecrets:
          - name: regcred

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-agendamento-deployment
  namespace: hackathon-28
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-agendamento
  template:
    metadata:
      labels:
        app: api-agendamento
    spec:
      containers:
      - name: api-agendamento
        image: cdoiche/hackathon-28-api-agendamento:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: ASPNETCORE_ENVIRONMENT
        - name: OTLP__ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: OTLP__ENDPOINT
        - name: ApiPacienteServiceUrl
          value: http://api-paciente-service
        - name: ApiMedicoServiceUrl
          value: http://api-medico-service
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_AGENDAMENTO
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: RABBIT_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: RABBITMQ_HOST
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: RABBITMQ_PORT
      imagePullSecrets:
          - name: regcred
