apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: hackathon-28
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # initContainers:
      # - name: fix-permissions
      #   image: busybox
      #   command: ["sh", "-c", "chmod -R 0777 /var/lib/postgresql/data"]
      #   volumeMounts:
      #   - name: postgres-storage
      #     mountPath: /var/lib/postgresql/data
      # - name: cleanup-data
      #   image: busybox
      #   command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/*"]
      #   volumeMounts:
      #   - name: postgres-storage
      #     mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        # - name: init-script-config
        #   mountPath: /docker-entrypoint-initdb.d/init-databases.sql
        #   subPath: init-databases.sql
        ports:
        - containerPort: 5432
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-hackathon-28-pvc
      
      # - name: init-script-config
      #   configMap:
      #     name: postgres-init-script


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: hackathon-28
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBITMQ_DEFAULT_PASS
        volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-storage
        persistentVolumeClaim:
          claimName: rabbitmq-hackathon-28-pvc