apiVersion: v1
kind: Service
metadata:
  name: api-agendamento-service
  namespace: hackathon-28
spec: 
  selector:
    app: api-agendamento
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-agendamento-service-ext
  namespace: hackathon-28
spec: 
  selector:
    app: api-agendamento
  ports:
    - protocol: TCP
      port: 5131
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: api-medico-service
  namespace: hackathon-28
spec: 
  selector:
    app: api-medico
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-medico-service-ext
  namespace: hackathon-28
spec: 
  selector:
    app: api-medico
  ports:
    - protocol: TCP
      port: 5132
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: api-paciente-service
  namespace: hackathon-28
spec: 
  selector:
    app: api-paciente
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-paciente-service-ext
  namespace: hackathon-28
spec: 
  selector:
    app: api-paciente
  ports:
    - protocol: TCP
      port: 5133
      targetPort: 8080
  type: LoadBalancer