apiVersion: batch/v1
kind: Job
metadata:
  name: apply-migrations-paciente-job
  namespace: hackathon-28
spec:
  template:
    spec:
      containers:
      - name: migrate-paciente-db
        image: cdoiche/hackathon-28-api-paciente:v1
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_PACIENTE
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        command: ["/bin/sh", "-c"]
        args:
        - |
          dotnet ef database update --context PacienteDbContext --project src/WebApi.csproj
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-migrations-medico-job
  namespace: hackathon-28
spec:
  template:
    spec:
      containers:
      - name: migrate-medico-db
        image: cdoiche/hackathon-28-api-medico:v1
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_MEDICO
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        command: ["/bin/sh", "-c"]
        args:
        - |
          dotnet ef database update --context ContextDB --project src/HackathonFiap.csproj
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-migrations-agendamento-job
  namespace: hackathon-28
spec:
  template:
    spec:
      containers:
      - name: migrate-agendament-db
        image: cdoiche/hackathon-28-api-agendamento:v1
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: api-configs
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB_AGENDAMENTO
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        command: ["/bin/sh", "-c"]
        args:
        - |
          dotnet ef database update --context ApplicationDbContext --project src/Fiap.Api.csproj
      restartPolicy: OnFailure