apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-hackathon-28-pv
  namespace: hackathon-28
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-hackathon-28-pvc
  namespace: hackathon-28
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-hackathon-28-pv
  namespace: hackathon-28
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rabbitmq
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-hackathon-28-pvc
  namespace: hackathon-28
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
