apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: hackathon-28
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: senha123!
  POSTGRES_DB_PACIENTE: db_paciente
  POSTGRES_DB_MEDICO: db_medico
  POSTGRES_DB_AGENDAMENTO: db_agendamento

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: hackathon-28
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
